swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport:        gmail
    username:         'contactwebmaster21@gmail.com'
    password:         '&Google123&'
    host:             localhost
    port:             465
    encryption:       ssl
    auth-mode:        login
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
