vich_uploader:
  db_driver: orm

  mappings:
    user:
      uri_prefix: '%uploads_prefix%/user'
      upload_destination: '%uploads_dir%/user'
      namer: vich_uploader.namer_hash
      delete_on_remove: true
      delete_on_update: true

    resume:
      uri_prefix: '%uploads_prefix%/resume'
      upload_destination: '%uploads_dir%/resume'
      namer: vich_uploader.namer_hash
      delete_on_remove: true
      delete_on_update: true

    company:
      uri_prefix: '%uploads_prefix%/company'
      upload_destination: '%uploads_dir%/company'
      namer: vich_uploader.namer_hash
      delete_on_remove: true
      delete_on_update: true
