register_newsletter:
  path: /{_locale}/newsletter
  controller: App\Controller\DefaultController::newsletter
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'
  methods: [GET, POST]
