# =======================================================
# |   Blog module
# =======================================================
blog_index:
  path: /blog
  controller: App\Controller\BlogController::index

article_create:
  path: /blog/new
  controller: App\Controller\BlogController::create

article_show:
  path: /blog/{slug}
  controller: App\Controller\BlogController::show

article_edit:
  path: /blog/{slug}/edit
  controller: App\Controller\BlogController::edit

article_delete:
  path: /blog/{slug}/delete
  controller: App\Controller\BlogController::delete
