companies_list:
  path: /companies
  controller: App\Controller\CompanyController::list

company_show:
  path: /company/{slug}
  controller: App\Controller\CompanyController::show

company_dashboard:
  path: /company/dashboard
  controller: App\Controller\CompanyController::dashboard

company_edit_profile:
  path: /company/edit-profile
  controller: App\Controller\CompanyController::editProfile

company_manage_jobs:
  path: /company/manage-jobs
  controller: App\Controller\CompanyController::manageJobs

company_manage_candidates:
  path: /company/manage-candidates
  controller: App\Controller\CompanyController::manageCandidates

company_shortlisted_resumes:
  path: /company/shortlisted
  controller: App\Controller\CompanyController::shortlistedResumes

company_messages:
  path: /company/messages
  controller: App\Controller\CompanyController::messages

company_pricing:
  path: /company/pricing
  controller: App\Controller\CompanyController::pricing
