companies_list:
  path: /companies
  controller: App\Controller\CompanyController::list

company_show:
  path: /company/{slug}
  controller: App\Controller\CompanyController::show

company_dashboard:
  path: /dashboard/company
  controller: App\Controller\CompanyController::dashboard

company_edit_profile:
  path: /dashboard/edit-profile
  controller: App\Controller\CompanyController::editProfile

company_manage_jobs:
  path: /dashboard/manage-jobs
  controller: App\Controller\CompanyController::manageJobs

company_manage_candidates:
  path: /dashboard/manage-candidates
  controller: App\Controller\CompanyController::manageCandidates

company_shortlisted_resumes:
  path: /dashboard/shortlisted
  controller: App\Controller\CompanyController::shortlistedResumes

company_job_applicants:
  path: /dashboard/ongoing/{slug}/{page<[1-9]\d*>}
  controller: App\Controller\CompanyController::jobApplicants
  defaults:
    page: 1

company_messages:
  path: /dashboard/messages
  controller: App\Controller\CompanyController::messages

company_pricing:
  path: /dashboard/pricing
  controller: App\Controller\CompanyController::pricing

company_cart:
  path: /dashboard/cart
  controller: App\Controller\CartController::list

add_to_cart:
  path: /dashboard/cart/add
  controller: App\Controller\CartController::add

remove_from_cart:
  path: /dashboard/cart/remove-item
  controller: App\Controller\CartController::removeItem