# Page d'accueil du site.
# Dans cette page on recupere directement le type d'etablissement que le visiteur cherche.
# La liste des categories est disponible dans parameters.
index:
  path: /
  controller: App\Controller\HomeController::index

about:
  path: /about-us
  controller: App\Controller\DefaultController::about

contact:
  path: /contact
  controller: App\Controller\DefaultController::contact
  methods: [GET, POST]
  # schemes: [https]

help_faq:
  path: /help-faq
  controller: App\Controller\DefaultController::helpFAQ

terms_conditions:
  path: /terms-conditions
  controller: App\Controller\DefaultController::termsCondtions

privacy:
  path: /privacy-policy
  controller: App\Controller\DefaultController::privacy

how_it_work:
  path: /how-it-work
  controller: App\Controller\DefaultController::howItWork

pricing:
  path: /pricing
  controller: App\Controller\DefaultController::pricing

newsletter:
  path: /subscribe
  controller: App\Controller\DefaultController::newsletter