<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190403072810 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'sqlite', 'Migration can only be executed safely on \'sqlite\'.');

        $this->addSql('DROP INDEX IDX_9F9F7D3C8BAC62AF');
        $this->addSql('DROP INDEX IDX_9F9F7D3CA76ED395');
        $this->addSql('DROP INDEX UNIQ_9F9F7D3C8864AF73');
        $this->addSql('DROP INDEX UNIQ_9F9F7D3C26ED0855');
        $this->addSql('CREATE TEMPORARY TABLE __temp__basic_info AS SELECT id, pricing_id, user_id, city_id, note_id, name, estab_name, address, web_site, description, created_at, updated_at, is_activated, phone, email FROM basic_info');
        $this->addSql('DROP TABLE basic_info');
        $this->addSql('CREATE TABLE basic_info (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, pricing_id INTEGER NOT NULL, user_id INTEGER NOT NULL, city_id INTEGER NOT NULL, note_id INTEGER DEFAULT NULL, name VARCHAR(164) NOT NULL COLLATE BINARY, estab_name VARCHAR(164) NOT NULL COLLATE BINARY, address VARCHAR(255) NOT NULL COLLATE BINARY, web_site VARCHAR(255) DEFAULT NULL COLLATE BINARY, description CLOB NOT NULL COLLATE BINARY, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, is_activated BOOLEAN NOT NULL, phone VARCHAR(255) NOT NULL COLLATE BINARY, email VARCHAR(255) DEFAULT NULL COLLATE BINARY, CONSTRAINT FK_9F9F7D3C8864AF73 FOREIGN KEY (pricing_id) REFERENCES pricings (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_9F9F7D3CA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_9F9F7D3C8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_9F9F7D3C26ED0855 FOREIGN KEY (note_id) REFERENCES note (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO basic_info (id, pricing_id, user_id, city_id, note_id, name, estab_name, address, web_site, description, created_at, updated_at, is_activated, phone, email) SELECT id, pricing_id, user_id, city_id, note_id, name, estab_name, address, web_site, description, created_at, updated_at, is_activated, phone, email FROM __temp__basic_info');
        $this->addSql('DROP TABLE __temp__basic_info');
        $this->addSql('CREATE INDEX IDX_9F9F7D3C8BAC62AF ON basic_info (city_id)');
        $this->addSql('CREATE INDEX IDX_9F9F7D3CA76ED395 ON basic_info (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F9F7D3C8864AF73 ON basic_info (pricing_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F9F7D3C26ED0855 ON basic_info (note_id)');
        $this->addSql('DROP INDEX UNIQ_E00CEDDE20ACB4DD');
        $this->addSql('DROP INDEX UNIQ_E00CEDDE23D6A298');
        $this->addSql('DROP INDEX UNIQ_E00CEDDE3DA992C3');
        $this->addSql('CREATE TEMPORARY TABLE __temp__booking AS SELECT id, dates_id, civility_id, establishment_info_id, username, email, phone, country, city, message FROM booking');
        $this->addSql('DROP TABLE booking');
        $this->addSql('CREATE TABLE booking (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, dates_id INTEGER NOT NULL, civility_id INTEGER NOT NULL, establishment_info_id INTEGER NOT NULL, username VARCHAR(255) NOT NULL COLLATE BINARY, email VARCHAR(255) NOT NULL COLLATE BINARY, phone VARCHAR(255) NOT NULL COLLATE BINARY, country VARCHAR(64) NOT NULL COLLATE BINARY, city VARCHAR(255) NOT NULL COLLATE BINARY, message CLOB DEFAULT NULL COLLATE BINARY, CONSTRAINT FK_E00CEDDE3DA992C3 FOREIGN KEY (dates_id) REFERENCES booking_dates (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E00CEDDE23D6A298 FOREIGN KEY (civility_id) REFERENCES civility (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E00CEDDE20ACB4DD FOREIGN KEY (establishment_info_id) REFERENCES basic_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO booking (id, dates_id, civility_id, establishment_info_id, username, email, phone, country, city, message) SELECT id, dates_id, civility_id, establishment_info_id, username, email, phone, country, city, message FROM __temp__booking');
        $this->addSql('DROP TABLE __temp__booking');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE20ACB4DD ON booking (establishment_info_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE23D6A298 ON booking (civility_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE3DA992C3 ON booking (dates_id)');
        $this->addSql('DROP INDEX IDX_9474526C1C678980');
        $this->addSql('CREATE TEMPORARY TABLE __temp__comment AS SELECT id, estab_id, content, created_at, updated_at, is_activated, username, email, note FROM comment');
        $this->addSql('DROP TABLE comment');
        $this->addSql('CREATE TABLE comment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, estab_id INTEGER NOT NULL, content VARCHAR(255) NOT NULL COLLATE BINARY, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, is_activated BOOLEAN DEFAULT NULL, username VARCHAR(255) NOT NULL COLLATE BINARY, email VARCHAR(255) DEFAULT NULL COLLATE BINARY, note INTEGER DEFAULT NULL, CONSTRAINT FK_9474526C1C678980 FOREIGN KEY (estab_id) REFERENCES basic_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO comment (id, estab_id, content, created_at, updated_at, is_activated, username, email, note) SELECT id, estab_id, content, created_at, updated_at, is_activated, username, email, note FROM __temp__comment');
        $this->addSql('DROP TABLE __temp__comment');
        $this->addSql('CREATE INDEX IDX_9474526C1C678980 ON comment (estab_id)');
        $this->addSql('DROP INDEX IDX_81398E091C678980');
        $this->addSql('DROP INDEX UNIQ_81398E0923D6A298');
        $this->addSql('CREATE TEMPORARY TABLE __temp__customer AS SELECT id, civility_id, estab_id, first_name, last_name, email, arriving_time, special_demands, created_at FROM customer');
        $this->addSql('DROP TABLE customer');
        $this->addSql('CREATE TABLE customer (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, civility_id INTEGER DEFAULT NULL, estab_id INTEGER DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL COLLATE BINARY, last_name VARCHAR(255) NOT NULL COLLATE BINARY, email VARCHAR(255) NOT NULL COLLATE BINARY, arriving_time TIME DEFAULT NULL, special_demands CLOB DEFAULT NULL COLLATE BINARY, created_at DATETIME NOT NULL, CONSTRAINT FK_81398E0923D6A298 FOREIGN KEY (civility_id) REFERENCES civility (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_81398E091C678980 FOREIGN KEY (estab_id) REFERENCES basic_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO customer (id, civility_id, estab_id, first_name, last_name, email, arriving_time, special_demands, created_at) SELECT id, civility_id, estab_id, first_name, last_name, email, arriving_time, special_demands, created_at FROM __temp__customer');
        $this->addSql('DROP TABLE __temp__customer');
        $this->addSql('CREATE INDEX IDX_81398E091C678980 ON customer (estab_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E0923D6A298 ON customer (civility_id)');
        $this->addSql('DROP INDEX UNIQ_4D7E6854517FE9FE');
        $this->addSql('DROP INDEX UNIQ_4D7E68548505D244');
        $this->addSql('DROP INDEX UNIQ_4D7E68545263402');
        $this->addSql('DROP INDEX UNIQ_4D7E6854CB893157');
        $this->addSql('DROP INDEX UNIQ_4D7E6854989D9B62');
        $this->addSql('CREATE TEMPORARY TABLE __temp__apartment AS SELECT id, info, facilities_id, rooms_equipment_id, equipment_id, name, created_at, updated_at, max_customers, slug FROM apartment');
        $this->addSql('DROP TABLE apartment');
        $this->addSql('CREATE TABLE apartment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, info INTEGER NOT NULL, facilities_id INTEGER DEFAULT NULL, rooms_equipment_id INTEGER DEFAULT NULL, equipment_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, max_customers INTEGER NOT NULL, slug VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_4D7E6854CB893157 FOREIGN KEY (info) REFERENCES basic_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_4D7E68545263402 FOREIGN KEY (facilities_id) REFERENCES facilities (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_4D7E68548505D244 FOREIGN KEY (rooms_equipment_id) REFERENCES room_equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_4D7E6854517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO apartment (id, info, facilities_id, rooms_equipment_id, equipment_id, name, created_at, updated_at, max_customers, slug) SELECT id, info, facilities_id, rooms_equipment_id, equipment_id, name, created_at, updated_at, max_customers, slug FROM __temp__apartment');
        $this->addSql('DROP TABLE __temp__apartment');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E6854517FE9FE ON apartment (equipment_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E68548505D244 ON apartment (rooms_equipment_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E68545263402 ON apartment (facilities_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E6854CB893157 ON apartment (info)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E6854989D9B62 ON apartment (slug)');
        $this->addSql('DROP INDEX IDX_82FA5792176DFE85');
        $this->addSql('CREATE TEMPORARY TABLE __temp__apartment_image AS SELECT id, apartment_id, alt, updated_at FROM apartment_image');
        $this->addSql('DROP TABLE apartment_image');
        $this->addSql('CREATE TABLE apartment_image (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, apartment_id INTEGER NOT NULL, alt VARCHAR(255) DEFAULT NULL COLLATE BINARY, updated_at DATETIME DEFAULT NULL, CONSTRAINT FK_82FA5792176DFE85 FOREIGN KEY (apartment_id) REFERENCES apartment (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO apartment_image (id, apartment_id, alt, updated_at) SELECT id, apartment_id, alt, updated_at FROM __temp__apartment_image');
        $this->addSql('DROP TABLE __temp__apartment_image');
        $this->addSql('CREATE INDEX IDX_82FA5792176DFE85 ON apartment_image (apartment_id)');
        $this->addSql('DROP INDEX IDX_E418F59382F1BAF4');
        $this->addSql('DROP INDEX IDX_E418F593517FE9FE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__equipment_language AS SELECT equipment_id, language_id FROM equipment_language');
        $this->addSql('DROP TABLE equipment_language');
        $this->addSql('CREATE TABLE equipment_language (equipment_id INTEGER NOT NULL, language_id INTEGER NOT NULL, PRIMARY KEY(equipment_id, language_id), CONSTRAINT FK_E418F593517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_E418F59382F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO equipment_language (equipment_id, language_id) SELECT equipment_id, language_id FROM __temp__equipment_language');
        $this->addSql('DROP TABLE __temp__equipment_language');
        $this->addSql('CREATE INDEX IDX_E418F59382F1BAF4 ON equipment_language (language_id)');
        $this->addSql('CREATE INDEX IDX_E418F593517FE9FE ON equipment_language (equipment_id)');
        $this->addSql('DROP INDEX UNIQ_3535ED95263402');
        $this->addSql('DROP INDEX UNIQ_3535ED98505D244');
        $this->addSql('DROP INDEX UNIQ_3535ED9517FE9FE');
        $this->addSql('DROP INDEX UNIQ_3535ED9CB893157');
        $this->addSql('DROP INDEX UNIQ_3535ED9989D9B62');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hotel AS SELECT id, info, equipment_id, rooms_equipment_id, facilities_id, name, created_at, updated_at, slug, stars, enabled FROM hotel');
        $this->addSql('DROP TABLE hotel');
        $this->addSql('CREATE TABLE hotel (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, info INTEGER NOT NULL, equipment_id INTEGER DEFAULT NULL, rooms_equipment_id INTEGER DEFAULT NULL, facilities_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, slug VARCHAR(255) NOT NULL COLLATE BINARY, stars INTEGER NOT NULL, enabled BOOLEAN DEFAULT NULL, CONSTRAINT FK_3535ED9CB893157 FOREIGN KEY (info) REFERENCES basic_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3535ED9517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3535ED98505D244 FOREIGN KEY (rooms_equipment_id) REFERENCES room_equipment (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_3535ED95263402 FOREIGN KEY (facilities_id) REFERENCES facilities (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO hotel (id, info, equipment_id, rooms_equipment_id, facilities_id, name, created_at, updated_at, slug, stars, enabled) SELECT id, info, equipment_id, rooms_equipment_id, facilities_id, name, created_at, updated_at, slug, stars, enabled FROM __temp__hotel');
        $this->addSql('DROP TABLE __temp__hotel');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED95263402 ON hotel (facilities_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED98505D244 ON hotel (rooms_equipment_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED9517FE9FE ON hotel (equipment_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED9CB893157 ON hotel (info)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED9989D9B62 ON hotel (slug)');
        $this->addSql('DROP INDEX IDX_26E9CA9B3243BB18');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hotel_image AS SELECT id, hotel_id, alt, updated_at FROM hotel_image');
        $this->addSql('DROP TABLE hotel_image');
        $this->addSql('CREATE TABLE hotel_image (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, hotel_id INTEGER NOT NULL, alt VARCHAR(255) DEFAULT NULL COLLATE BINARY, updated_at DATETIME DEFAULT NULL, CONSTRAINT FK_26E9CA9B3243BB18 FOREIGN KEY (hotel_id) REFERENCES hotel (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO hotel_image (id, hotel_id, alt, updated_at) SELECT id, hotel_id, alt, updated_at FROM __temp__hotel_image');
        $this->addSql('DROP TABLE __temp__hotel_image');
        $this->addSql('CREATE INDEX IDX_26E9CA9B3243BB18 ON hotel_image (hotel_id)');
        $this->addSql('DROP INDEX UNIQ_67D5399DCB893157');
        $this->addSql('CREATE TEMPORARY TABLE __temp__house AS SELECT id, info, name FROM house');
        $this->addSql('DROP TABLE house');
        $this->addSql('CREATE TABLE house (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, info INTEGER NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_67D5399DCB893157 FOREIGN KEY (info) REFERENCES basic_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO house (id, info, name) SELECT id, info, name FROM __temp__house');
        $this->addSql('DROP TABLE __temp__house');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_67D5399DCB893157 ON house (info)');
        $this->addSql('DROP INDEX IDX_42F2DAAC54C8C93');
        $this->addSql('DROP INDEX IDX_42F2DAA12469DE2');
        $this->addSql('DROP INDEX IDX_42F2DAAA76ED395');
        $this->addSql('DROP INDEX IDX_42F2DAAB08FA272');
        $this->addSql('DROP INDEX UNIQ_42F2DAA989D9B62');
        $this->addSql('CREATE TEMPORARY TABLE __temp__immovable AS SELECT id, district_id, user_id, category_id, type_id, area, length, width, construction_year, nb_salons, nb_toilets, nb_rooms, created_at, updated_at, slug, description, price, monthly_price, type_name FROM immovable');
        $this->addSql('DROP TABLE immovable');
        $this->addSql('CREATE TABLE immovable (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, district_id INTEGER DEFAULT NULL, user_id INTEGER NOT NULL, category_id INTEGER NOT NULL, type_id INTEGER NOT NULL, area VARCHAR(255) DEFAULT NULL COLLATE BINARY, length VARCHAR(255) DEFAULT NULL COLLATE BINARY, width VARCHAR(255) DEFAULT NULL COLLATE BINARY, construction_year VARCHAR(255) DEFAULT NULL COLLATE BINARY, nb_salons INTEGER DEFAULT NULL, nb_toilets INTEGER DEFAULT NULL, nb_rooms INTEGER DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, slug VARCHAR(255) NOT NULL COLLATE BINARY, description VARCHAR(255) DEFAULT NULL COLLATE BINARY, price VARCHAR(255) DEFAULT NULL COLLATE BINARY, monthly_price VARCHAR(255) DEFAULT NULL COLLATE BINARY, type_name VARCHAR(255) NOT NULL COLLATE BINARY, CONSTRAINT FK_42F2DAAB08FA272 FOREIGN KEY (district_id) REFERENCES district (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_42F2DAAA76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_42F2DAA12469DE2 FOREIGN KEY (category_id) REFERENCES immovable_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_42F2DAAC54C8C93 FOREIGN KEY (type_id) REFERENCES immovable_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO immovable (id, district_id, user_id, category_id, type_id, area, length, width, construction_year, nb_salons, nb_toilets, nb_rooms, created_at, updated_at, slug, description, price, monthly_price, type_name) SELECT id, district_id, user_id, category_id, type_id, area, length, width, construction_year, nb_salons, nb_toilets, nb_rooms, created_at, updated_at, slug, description, price, monthly_price, type_name FROM __temp__immovable');
        $this->addSql('DROP TABLE __temp__immovable');
        $this->addSql('CREATE INDEX IDX_42F2DAAC54C8C93 ON immovable (type_id)');
        $this->addSql('CREATE INDEX IDX_42F2DAA12469DE2 ON immovable (category_id)');
        $this->addSql('CREATE INDEX IDX_42F2DAAA76ED395 ON immovable (user_id)');
        $this->addSql('CREATE INDEX IDX_42F2DAAB08FA272 ON immovable (district_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_42F2DAA989D9B62 ON immovable (slug)');
        $this->addSql('DROP INDEX IDX_318B264A39557A34');
        $this->addSql('CREATE TEMPORARY TABLE __temp__immovable_image AS SELECT id, immovable_id, alt, updated_at FROM immovable_image');
        $this->addSql('DROP TABLE immovable_image');
        $this->addSql('CREATE TABLE immovable_image (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, immovable_id INTEGER NOT NULL, alt VARCHAR(255) DEFAULT NULL COLLATE BINARY, updated_at DATETIME DEFAULT NULL, CONSTRAINT FK_318B264A39557A34 FOREIGN KEY (immovable_id) REFERENCES immovable (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO immovable_image (id, immovable_id, alt, updated_at) SELECT id, immovable_id, alt, updated_at FROM __temp__immovable_image');
        $this->addSql('DROP TABLE __temp__immovable_image');
        $this->addSql('CREATE INDEX IDX_318B264A39557A34 ON immovable_image (immovable_id)');
        $this->addSql('DROP INDEX UNIQ_EB95123FCB893157');
        $this->addSql('DROP INDEX UNIQ_EB95123F989D9B62');
        $this->addSql('CREATE TEMPORARY TABLE __temp__restaurant AS SELECT id, info, name, slug, created_at, updated_at, has_shipment, shipment_price FROM restaurant');
        $this->addSql('DROP TABLE restaurant');
        $this->addSql('CREATE TABLE restaurant (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, info INTEGER NOT NULL, name VARCHAR(255) NOT NULL COLLATE BINARY, slug VARCHAR(255) NOT NULL COLLATE BINARY, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, has_shipment BOOLEAN DEFAULT NULL, shipment_price VARCHAR(255) DEFAULT NULL COLLATE BINARY, CONSTRAINT FK_EB95123FCB893157 FOREIGN KEY (info) REFERENCES basic_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO restaurant (id, info, name, slug, created_at, updated_at, has_shipment, shipment_price) SELECT id, info, name, slug, created_at, updated_at, has_shipment, shipment_price FROM __temp__restaurant');
        $this->addSql('DROP TABLE __temp__restaurant');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB95123FCB893157 ON restaurant (info)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB95123F989D9B62 ON restaurant (slug)');
        $this->addSql('DROP INDEX IDX_8F20B78EB1E7706E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__restaurant_image AS SELECT id, restaurant_id, alt, updated_at FROM restaurant_image');
        $this->addSql('DROP TABLE restaurant_image');
        $this->addSql('CREATE TABLE restaurant_image (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, restaurant_id INTEGER NOT NULL, alt VARCHAR(255) DEFAULT NULL COLLATE BINARY, updated_at DATETIME DEFAULT NULL, CONSTRAINT FK_8F20B78EB1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO restaurant_image (id, restaurant_id, alt, updated_at) SELECT id, restaurant_id, alt, updated_at FROM __temp__restaurant_image');
        $this->addSql('DROP TABLE __temp__restaurant_image');
        $this->addSql('CREATE INDEX IDX_8F20B78EB1E7706E ON restaurant_image (restaurant_id)');
        $this->addSql('DROP INDEX IDX_950FB5138248176');
        $this->addSql('CREATE TEMPORARY TABLE __temp__monthly_price AS SELECT id, currency_id, value FROM monthly_price');
        $this->addSql('DROP TABLE monthly_price');
        $this->addSql('CREATE TABLE monthly_price (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, currency_id INTEGER NOT NULL, value INTEGER NOT NULL, CONSTRAINT FK_950FB5138248176 FOREIGN KEY (currency_id) REFERENCES currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO monthly_price (id, currency_id, value) SELECT id, currency_id, value FROM __temp__monthly_price');
        $this->addSql('DROP TABLE __temp__monthly_price');
        $this->addSql('CREATE INDEX IDX_950FB5138248176 ON monthly_price (currency_id)');
        $this->addSql('DROP INDEX IDX_578CDCF938248176');
        $this->addSql('CREATE TEMPORARY TABLE __temp__nightly_price AS SELECT id, currency_id, value FROM nightly_price');
        $this->addSql('DROP TABLE nightly_price');
        $this->addSql('CREATE TABLE nightly_price (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, currency_id INTEGER NOT NULL, value INTEGER NOT NULL, CONSTRAINT FK_578CDCF938248176 FOREIGN KEY (currency_id) REFERENCES currency (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO nightly_price (id, currency_id, value) SELECT id, currency_id, value FROM __temp__nightly_price');
        $this->addSql('DROP TABLE __temp__nightly_price');
        $this->addSql('CREATE INDEX IDX_578CDCF938248176 ON nightly_price (currency_id)');
        $this->addSql('DROP INDEX IDX_A43B5FB1AE5D0B3D');
        $this->addSql('DROP INDEX IDX_A43B5FB1FD55E6C5');
        $this->addSql('CREATE TEMPORARY TABLE __temp__pricings AS SELECT id, nightly_id, monthly_id FROM pricings');
        $this->addSql('DROP TABLE pricings');
        $this->addSql('CREATE TABLE pricings (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nightly_id INTEGER NOT NULL, monthly_id INTEGER DEFAULT NULL, CONSTRAINT FK_A43B5FB1FD55E6C5 FOREIGN KEY (nightly_id) REFERENCES nightly_price (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_A43B5FB1AE5D0B3D FOREIGN KEY (monthly_id) REFERENCES monthly_price (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO pricings (id, nightly_id, monthly_id) SELECT id, nightly_id, monthly_id FROM __temp__pricings');
        $this->addSql('DROP TABLE __temp__pricings');
        $this->addSql('CREATE INDEX IDX_A43B5FB1AE5D0B3D ON pricings (monthly_id)');
        $this->addSql('CREATE INDEX IDX_A43B5FB1FD55E6C5 ON pricings (nightly_id)');
        $this->addSql('CREATE TEMPORARY TABLE __temp__purchase AS SELECT id, dates_id, estab_id, firstname, lastname, email, country, phone_number, persons, message, check_in_hours, state, created_at, confirmed_at, cancelled_at FROM purchase');
        $this->addSql('DROP TABLE purchase');
        $this->addSql('CREATE TABLE purchase (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, dates_id INTEGER NOT NULL, estab_id INTEGER NOT NULL, firstname VARCHAR(255) DEFAULT NULL COLLATE BINARY, lastname VARCHAR(255) NOT NULL COLLATE BINARY, email VARCHAR(255) NOT NULL COLLATE BINARY, country VARCHAR(255) NOT NULL COLLATE BINARY, phone_number VARCHAR(255) NOT NULL COLLATE BINARY, persons INTEGER DEFAULT NULL, message CLOB DEFAULT NULL COLLATE BINARY, check_in_hours VARCHAR(255) DEFAULT NULL COLLATE BINARY, state VARCHAR(255) NOT NULL COLLATE BINARY, created_at DATETIME NOT NULL, confirmed_at DATETIME DEFAULT NULL, cancelled_at DATETIME DEFAULT NULL, CONSTRAINT FK_6117D13B3DA992C3 FOREIGN KEY (dates_id) REFERENCES booking_dates (id) NOT DEFERRABLE INITIALLY IMMEDIATE, CONSTRAINT FK_6117D13B1C678980 FOREIGN KEY (estab_id) REFERENCES basic_info (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO purchase (id, dates_id, estab_id, firstname, lastname, email, country, phone_number, persons, message, check_in_hours, state, created_at, confirmed_at, cancelled_at) SELECT id, dates_id, estab_id, firstname, lastname, email, country, phone_number, persons, message, check_in_hours, state, created_at, confirmed_at, cancelled_at FROM __temp__purchase');
        $this->addSql('DROP TABLE __temp__purchase');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6117D13B3DA992C3 ON purchase (dates_id)');
        $this->addSql('CREATE INDEX IDX_6117D13B1C678980 ON purchase (estab_id)');
        $this->addSql('DROP INDEX UNIQ_88BDF3E992FC23A8');
        $this->addSql('DROP INDEX UNIQ_88BDF3E9A0D96FBF');
        $this->addSql('DROP INDEX UNIQ_88BDF3E9C05FB297');
        $this->addSql('DROP INDEX UNIQ_88BDF3E986383B10');
        $this->addSql('CREATE TEMPORARY TABLE __temp__app_user AS SELECT id, avatar_id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, phone_number, submitted_at, country, city, locale FROM app_user');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('CREATE TABLE app_user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, avatar_id INTEGER DEFAULT NULL, username VARCHAR(180) NOT NULL COLLATE BINARY, username_canonical VARCHAR(180) NOT NULL COLLATE BINARY, email VARCHAR(180) NOT NULL COLLATE BINARY, email_canonical VARCHAR(180) NOT NULL COLLATE BINARY, enabled BOOLEAN NOT NULL, salt VARCHAR(255) DEFAULT NULL COLLATE BINARY, password VARCHAR(255) NOT NULL COLLATE BINARY, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL COLLATE BINARY, password_requested_at DATETIME DEFAULT NULL, roles CLOB NOT NULL COLLATE BINARY --(DC2Type:array)
        , phone_number VARCHAR(255) DEFAULT NULL COLLATE BINARY, submitted_at DATETIME NOT NULL, country VARCHAR(255) DEFAULT NULL COLLATE BINARY, city VARCHAR(255) DEFAULT NULL COLLATE BINARY, locale VARCHAR(10) DEFAULT NULL COLLATE BINARY, CONSTRAINT FK_88BDF3E986383B10 FOREIGN KEY (avatar_id) REFERENCES avatar (id) NOT DEFERRABLE INITIALLY IMMEDIATE)');
        $this->addSql('INSERT INTO app_user (id, avatar_id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, phone_number, submitted_at, country, city, locale) SELECT id, avatar_id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, phone_number, submitted_at, country, city, locale FROM __temp__app_user');
        $this->addSql('DROP TABLE __temp__app_user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E992FC23A8 ON app_user (username_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9A0D96FBF ON app_user (email_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9C05FB297 ON app_user (confirmation_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E986383B10 ON app_user (avatar_id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'sqlite', 'Migration can only be executed safely on \'sqlite\'.');

        $this->addSql('DROP INDEX UNIQ_4D7E6854989D9B62');
        $this->addSql('DROP INDEX UNIQ_4D7E6854CB893157');
        $this->addSql('DROP INDEX UNIQ_4D7E68545263402');
        $this->addSql('DROP INDEX UNIQ_4D7E68548505D244');
        $this->addSql('DROP INDEX UNIQ_4D7E6854517FE9FE');
        $this->addSql('CREATE TEMPORARY TABLE __temp__apartment AS SELECT id, info, facilities_id, rooms_equipment_id, equipment_id, name, created_at, updated_at, max_customers, slug FROM apartment');
        $this->addSql('DROP TABLE apartment');
        $this->addSql('CREATE TABLE apartment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, info INTEGER NOT NULL, facilities_id INTEGER DEFAULT NULL, rooms_equipment_id INTEGER DEFAULT NULL, equipment_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, max_customers INTEGER NOT NULL, slug VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO apartment (id, info, facilities_id, rooms_equipment_id, equipment_id, name, created_at, updated_at, max_customers, slug) SELECT id, info, facilities_id, rooms_equipment_id, equipment_id, name, created_at, updated_at, max_customers, slug FROM __temp__apartment');
        $this->addSql('DROP TABLE __temp__apartment');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E6854989D9B62 ON apartment (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E6854CB893157 ON apartment (info)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E68545263402 ON apartment (facilities_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E68548505D244 ON apartment (rooms_equipment_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4D7E6854517FE9FE ON apartment (equipment_id)');
        $this->addSql('DROP INDEX IDX_82FA5792176DFE85');
        $this->addSql('CREATE TEMPORARY TABLE __temp__apartment_image AS SELECT id, apartment_id, alt, updated_at FROM apartment_image');
        $this->addSql('DROP TABLE apartment_image');
        $this->addSql('CREATE TABLE apartment_image (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, apartment_id INTEGER NOT NULL, alt VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('INSERT INTO apartment_image (id, apartment_id, alt, updated_at) SELECT id, apartment_id, alt, updated_at FROM __temp__apartment_image');
        $this->addSql('DROP TABLE __temp__apartment_image');
        $this->addSql('CREATE INDEX IDX_82FA5792176DFE85 ON apartment_image (apartment_id)');
        $this->addSql('DROP INDEX UNIQ_88BDF3E992FC23A8');
        $this->addSql('DROP INDEX UNIQ_88BDF3E9A0D96FBF');
        $this->addSql('DROP INDEX UNIQ_88BDF3E9C05FB297');
        $this->addSql('DROP INDEX UNIQ_88BDF3E986383B10');
        $this->addSql('CREATE TEMPORARY TABLE __temp__app_user AS SELECT id, avatar_id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, phone_number, submitted_at, country, city, locale FROM app_user');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('CREATE TABLE app_user (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, avatar_id INTEGER DEFAULT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles CLOB NOT NULL --(DC2Type:array)
        , phone_number VARCHAR(255) DEFAULT NULL, submitted_at DATETIME NOT NULL, country VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, locale VARCHAR(10) DEFAULT NULL, is_active BOOLEAN DEFAULT NULL)');
        $this->addSql('INSERT INTO app_user (id, avatar_id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, phone_number, submitted_at, country, city, locale) SELECT id, avatar_id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, phone_number, submitted_at, country, city, locale FROM __temp__app_user');
        $this->addSql('DROP TABLE __temp__app_user');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E992FC23A8 ON app_user (username_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9A0D96FBF ON app_user (email_canonical)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9C05FB297 ON app_user (confirmation_token)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E986383B10 ON app_user (avatar_id)');
        $this->addSql('DROP INDEX UNIQ_9F9F7D3C8864AF73');
        $this->addSql('DROP INDEX IDX_9F9F7D3CA76ED395');
        $this->addSql('DROP INDEX IDX_9F9F7D3C8BAC62AF');
        $this->addSql('DROP INDEX UNIQ_9F9F7D3C26ED0855');
        $this->addSql('CREATE TEMPORARY TABLE __temp__basic_info AS SELECT id, pricing_id, user_id, city_id, note_id, name, estab_name, address, email, web_site, description, created_at, updated_at, is_activated, phone FROM basic_info');
        $this->addSql('DROP TABLE basic_info');
        $this->addSql('CREATE TABLE basic_info (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, pricing_id INTEGER NOT NULL, user_id INTEGER NOT NULL, city_id INTEGER NOT NULL, note_id INTEGER DEFAULT NULL, name VARCHAR(164) NOT NULL, estab_name VARCHAR(164) NOT NULL, address VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, web_site VARCHAR(255) DEFAULT NULL, description CLOB NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, is_activated BOOLEAN NOT NULL, phone VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO basic_info (id, pricing_id, user_id, city_id, note_id, name, estab_name, address, email, web_site, description, created_at, updated_at, is_activated, phone) SELECT id, pricing_id, user_id, city_id, note_id, name, estab_name, address, email, web_site, description, created_at, updated_at, is_activated, phone FROM __temp__basic_info');
        $this->addSql('DROP TABLE __temp__basic_info');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F9F7D3C8864AF73 ON basic_info (pricing_id)');
        $this->addSql('CREATE INDEX IDX_9F9F7D3CA76ED395 ON basic_info (user_id)');
        $this->addSql('CREATE INDEX IDX_9F9F7D3C8BAC62AF ON basic_info (city_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9F9F7D3C26ED0855 ON basic_info (note_id)');
        $this->addSql('DROP INDEX UNIQ_E00CEDDE3DA992C3');
        $this->addSql('DROP INDEX UNIQ_E00CEDDE23D6A298');
        $this->addSql('DROP INDEX UNIQ_E00CEDDE20ACB4DD');
        $this->addSql('CREATE TEMPORARY TABLE __temp__booking AS SELECT id, dates_id, civility_id, establishment_info_id, username, email, phone, country, city, message FROM booking');
        $this->addSql('DROP TABLE booking');
        $this->addSql('CREATE TABLE booking (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, dates_id INTEGER NOT NULL, civility_id INTEGER NOT NULL, establishment_info_id INTEGER NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, country VARCHAR(64) NOT NULL, city VARCHAR(255) NOT NULL, message CLOB DEFAULT NULL)');
        $this->addSql('INSERT INTO booking (id, dates_id, civility_id, establishment_info_id, username, email, phone, country, city, message) SELECT id, dates_id, civility_id, establishment_info_id, username, email, phone, country, city, message FROM __temp__booking');
        $this->addSql('DROP TABLE __temp__booking');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE3DA992C3 ON booking (dates_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE23D6A298 ON booking (civility_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E00CEDDE20ACB4DD ON booking (establishment_info_id)');
        $this->addSql('DROP INDEX IDX_9474526C1C678980');
        $this->addSql('CREATE TEMPORARY TABLE __temp__comment AS SELECT id, estab_id, content, created_at, updated_at, is_activated, username, email, note FROM comment');
        $this->addSql('DROP TABLE comment');
        $this->addSql('CREATE TABLE comment (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, estab_id INTEGER NOT NULL, content VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, is_activated BOOLEAN DEFAULT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) DEFAULT NULL, note INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO comment (id, estab_id, content, created_at, updated_at, is_activated, username, email, note) SELECT id, estab_id, content, created_at, updated_at, is_activated, username, email, note FROM __temp__comment');
        $this->addSql('DROP TABLE __temp__comment');
        $this->addSql('CREATE INDEX IDX_9474526C1C678980 ON comment (estab_id)');
        $this->addSql('DROP INDEX UNIQ_81398E0923D6A298');
        $this->addSql('DROP INDEX IDX_81398E091C678980');
        $this->addSql('CREATE TEMPORARY TABLE __temp__customer AS SELECT id, civility_id, estab_id, first_name, last_name, email, arriving_time, special_demands, created_at FROM customer');
        $this->addSql('DROP TABLE customer');
        $this->addSql('CREATE TABLE customer (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, civility_id INTEGER DEFAULT NULL, estab_id INTEGER DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, arriving_time TIME DEFAULT NULL, special_demands CLOB DEFAULT NULL, created_at DATETIME NOT NULL)');
        $this->addSql('INSERT INTO customer (id, civility_id, estab_id, first_name, last_name, email, arriving_time, special_demands, created_at) SELECT id, civility_id, estab_id, first_name, last_name, email, arriving_time, special_demands, created_at FROM __temp__customer');
        $this->addSql('DROP TABLE __temp__customer');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E0923D6A298 ON customer (civility_id)');
        $this->addSql('CREATE INDEX IDX_81398E091C678980 ON customer (estab_id)');
        $this->addSql('DROP INDEX IDX_E418F593517FE9FE');
        $this->addSql('DROP INDEX IDX_E418F59382F1BAF4');
        $this->addSql('CREATE TEMPORARY TABLE __temp__equipment_language AS SELECT equipment_id, language_id FROM equipment_language');
        $this->addSql('DROP TABLE equipment_language');
        $this->addSql('CREATE TABLE equipment_language (equipment_id INTEGER NOT NULL, language_id INTEGER NOT NULL, PRIMARY KEY(equipment_id, language_id))');
        $this->addSql('INSERT INTO equipment_language (equipment_id, language_id) SELECT equipment_id, language_id FROM __temp__equipment_language');
        $this->addSql('DROP TABLE __temp__equipment_language');
        $this->addSql('CREATE INDEX IDX_E418F593517FE9FE ON equipment_language (equipment_id)');
        $this->addSql('CREATE INDEX IDX_E418F59382F1BAF4 ON equipment_language (language_id)');
        $this->addSql('DROP INDEX UNIQ_3535ED9989D9B62');
        $this->addSql('DROP INDEX UNIQ_3535ED9CB893157');
        $this->addSql('DROP INDEX UNIQ_3535ED9517FE9FE');
        $this->addSql('DROP INDEX UNIQ_3535ED98505D244');
        $this->addSql('DROP INDEX UNIQ_3535ED95263402');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hotel AS SELECT id, info, equipment_id, rooms_equipment_id, facilities_id, name, created_at, updated_at, slug, stars, enabled FROM hotel');
        $this->addSql('DROP TABLE hotel');
        $this->addSql('CREATE TABLE hotel (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, info INTEGER NOT NULL, equipment_id INTEGER DEFAULT NULL, rooms_equipment_id INTEGER DEFAULT NULL, facilities_id INTEGER DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, slug VARCHAR(255) NOT NULL, stars INTEGER NOT NULL, enabled BOOLEAN DEFAULT NULL)');
        $this->addSql('INSERT INTO hotel (id, info, equipment_id, rooms_equipment_id, facilities_id, name, created_at, updated_at, slug, stars, enabled) SELECT id, info, equipment_id, rooms_equipment_id, facilities_id, name, created_at, updated_at, slug, stars, enabled FROM __temp__hotel');
        $this->addSql('DROP TABLE __temp__hotel');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED9989D9B62 ON hotel (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED9CB893157 ON hotel (info)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED9517FE9FE ON hotel (equipment_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED98505D244 ON hotel (rooms_equipment_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3535ED95263402 ON hotel (facilities_id)');
        $this->addSql('DROP INDEX IDX_26E9CA9B3243BB18');
        $this->addSql('CREATE TEMPORARY TABLE __temp__hotel_image AS SELECT id, hotel_id, alt, updated_at FROM hotel_image');
        $this->addSql('DROP TABLE hotel_image');
        $this->addSql('CREATE TABLE hotel_image (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, hotel_id INTEGER NOT NULL, alt VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('INSERT INTO hotel_image (id, hotel_id, alt, updated_at) SELECT id, hotel_id, alt, updated_at FROM __temp__hotel_image');
        $this->addSql('DROP TABLE __temp__hotel_image');
        $this->addSql('CREATE INDEX IDX_26E9CA9B3243BB18 ON hotel_image (hotel_id)');
        $this->addSql('DROP INDEX UNIQ_67D5399DCB893157');
        $this->addSql('CREATE TEMPORARY TABLE __temp__house AS SELECT id, info, name FROM house');
        $this->addSql('DROP TABLE house');
        $this->addSql('CREATE TABLE house (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, info INTEGER NOT NULL, name VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO house (id, info, name) SELECT id, info, name FROM __temp__house');
        $this->addSql('DROP TABLE __temp__house');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_67D5399DCB893157 ON house (info)');
        $this->addSql('DROP INDEX UNIQ_42F2DAA989D9B62');
        $this->addSql('DROP INDEX IDX_42F2DAAB08FA272');
        $this->addSql('DROP INDEX IDX_42F2DAAA76ED395');
        $this->addSql('DROP INDEX IDX_42F2DAA12469DE2');
        $this->addSql('DROP INDEX IDX_42F2DAAC54C8C93');
        $this->addSql('CREATE TEMPORARY TABLE __temp__immovable AS SELECT id, district_id, user_id, category_id, type_id, area, length, width, construction_year, nb_salons, nb_toilets, nb_rooms, created_at, updated_at, slug, description, price, monthly_price, type_name FROM immovable');
        $this->addSql('DROP TABLE immovable');
        $this->addSql('CREATE TABLE immovable (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, district_id INTEGER DEFAULT NULL, user_id INTEGER NOT NULL, category_id INTEGER NOT NULL, type_id INTEGER NOT NULL, area VARCHAR(255) DEFAULT NULL, length VARCHAR(255) DEFAULT NULL, width VARCHAR(255) DEFAULT NULL, construction_year VARCHAR(255) DEFAULT NULL, nb_salons INTEGER DEFAULT NULL, nb_toilets INTEGER DEFAULT NULL, nb_rooms INTEGER DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, slug VARCHAR(255) NOT NULL, description VARCHAR(255) DEFAULT NULL, price VARCHAR(255) DEFAULT NULL, monthly_price VARCHAR(255) DEFAULT NULL, type_name VARCHAR(255) NOT NULL)');
        $this->addSql('INSERT INTO immovable (id, district_id, user_id, category_id, type_id, area, length, width, construction_year, nb_salons, nb_toilets, nb_rooms, created_at, updated_at, slug, description, price, monthly_price, type_name) SELECT id, district_id, user_id, category_id, type_id, area, length, width, construction_year, nb_salons, nb_toilets, nb_rooms, created_at, updated_at, slug, description, price, monthly_price, type_name FROM __temp__immovable');
        $this->addSql('DROP TABLE __temp__immovable');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_42F2DAA989D9B62 ON immovable (slug)');
        $this->addSql('CREATE INDEX IDX_42F2DAAB08FA272 ON immovable (district_id)');
        $this->addSql('CREATE INDEX IDX_42F2DAAA76ED395 ON immovable (user_id)');
        $this->addSql('CREATE INDEX IDX_42F2DAA12469DE2 ON immovable (category_id)');
        $this->addSql('CREATE INDEX IDX_42F2DAAC54C8C93 ON immovable (type_id)');
        $this->addSql('DROP INDEX IDX_318B264A39557A34');
        $this->addSql('CREATE TEMPORARY TABLE __temp__immovable_image AS SELECT id, immovable_id, alt, updated_at FROM immovable_image');
        $this->addSql('DROP TABLE immovable_image');
        $this->addSql('CREATE TABLE immovable_image (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, immovable_id INTEGER NOT NULL, alt VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('INSERT INTO immovable_image (id, immovable_id, alt, updated_at) SELECT id, immovable_id, alt, updated_at FROM __temp__immovable_image');
        $this->addSql('DROP TABLE __temp__immovable_image');
        $this->addSql('CREATE INDEX IDX_318B264A39557A34 ON immovable_image (immovable_id)');
        $this->addSql('DROP INDEX IDX_950FB5138248176');
        $this->addSql('CREATE TEMPORARY TABLE __temp__monthly_price AS SELECT id, currency_id, value FROM monthly_price');
        $this->addSql('DROP TABLE monthly_price');
        $this->addSql('CREATE TABLE monthly_price (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, currency_id INTEGER NOT NULL, value INTEGER NOT NULL)');
        $this->addSql('INSERT INTO monthly_price (id, currency_id, value) SELECT id, currency_id, value FROM __temp__monthly_price');
        $this->addSql('DROP TABLE __temp__monthly_price');
        $this->addSql('CREATE INDEX IDX_950FB5138248176 ON monthly_price (currency_id)');
        $this->addSql('DROP INDEX IDX_578CDCF938248176');
        $this->addSql('CREATE TEMPORARY TABLE __temp__nightly_price AS SELECT id, currency_id, value FROM nightly_price');
        $this->addSql('DROP TABLE nightly_price');
        $this->addSql('CREATE TABLE nightly_price (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, currency_id INTEGER NOT NULL, value INTEGER NOT NULL)');
        $this->addSql('INSERT INTO nightly_price (id, currency_id, value) SELECT id, currency_id, value FROM __temp__nightly_price');
        $this->addSql('DROP TABLE __temp__nightly_price');
        $this->addSql('CREATE INDEX IDX_578CDCF938248176 ON nightly_price (currency_id)');
        $this->addSql('DROP INDEX IDX_A43B5FB1FD55E6C5');
        $this->addSql('DROP INDEX IDX_A43B5FB1AE5D0B3D');
        $this->addSql('CREATE TEMPORARY TABLE __temp__pricings AS SELECT id, nightly_id, monthly_id FROM pricings');
        $this->addSql('DROP TABLE pricings');
        $this->addSql('CREATE TABLE pricings (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, nightly_id INTEGER NOT NULL, monthly_id INTEGER DEFAULT NULL)');
        $this->addSql('INSERT INTO pricings (id, nightly_id, monthly_id) SELECT id, nightly_id, monthly_id FROM __temp__pricings');
        $this->addSql('DROP TABLE __temp__pricings');
        $this->addSql('CREATE INDEX IDX_A43B5FB1FD55E6C5 ON pricings (nightly_id)');
        $this->addSql('CREATE INDEX IDX_A43B5FB1AE5D0B3D ON pricings (monthly_id)');
        $this->addSql('DROP INDEX UNIQ_6117D13B3DA992C3');
        $this->addSql('DROP INDEX IDX_6117D13B1C678980');
        $this->addSql('CREATE TEMPORARY TABLE __temp__purchase AS SELECT id, dates_id, estab_id, firstname, lastname, email, country, phone_number, persons, message, check_in_hours, state, created_at, confirmed_at, cancelled_at FROM purchase');
        $this->addSql('DROP TABLE purchase');
        $this->addSql('CREATE TABLE purchase (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, dates_id INTEGER NOT NULL, estab_id INTEGER NOT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, country VARCHAR(255) NOT NULL, phone_number VARCHAR(255) NOT NULL, persons INTEGER DEFAULT NULL, message CLOB DEFAULT NULL, check_in_hours VARCHAR(255) DEFAULT NULL, state VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, confirmed_at DATETIME DEFAULT NULL, cancelled_at DATETIME DEFAULT NULL)');
        $this->addSql('INSERT INTO purchase (id, dates_id, estab_id, firstname, lastname, email, country, phone_number, persons, message, check_in_hours, state, created_at, confirmed_at, cancelled_at) SELECT id, dates_id, estab_id, firstname, lastname, email, country, phone_number, persons, message, check_in_hours, state, created_at, confirmed_at, cancelled_at FROM __temp__purchase');
        $this->addSql('DROP TABLE __temp__purchase');
        $this->addSql('DROP INDEX UNIQ_EB95123F989D9B62');
        $this->addSql('DROP INDEX UNIQ_EB95123FCB893157');
        $this->addSql('CREATE TEMPORARY TABLE __temp__restaurant AS SELECT id, info, name, slug, created_at, updated_at, has_shipment, shipment_price FROM restaurant');
        $this->addSql('DROP TABLE restaurant');
        $this->addSql('CREATE TABLE restaurant (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, info INTEGER NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, has_shipment BOOLEAN DEFAULT NULL, shipment_price VARCHAR(255) DEFAULT NULL)');
        $this->addSql('INSERT INTO restaurant (id, info, name, slug, created_at, updated_at, has_shipment, shipment_price) SELECT id, info, name, slug, created_at, updated_at, has_shipment, shipment_price FROM __temp__restaurant');
        $this->addSql('DROP TABLE __temp__restaurant');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB95123F989D9B62 ON restaurant (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB95123FCB893157 ON restaurant (info)');
        $this->addSql('DROP INDEX IDX_8F20B78EB1E7706E');
        $this->addSql('CREATE TEMPORARY TABLE __temp__restaurant_image AS SELECT id, restaurant_id, alt, updated_at FROM restaurant_image');
        $this->addSql('DROP TABLE restaurant_image');
        $this->addSql('CREATE TABLE restaurant_image (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, restaurant_id INTEGER NOT NULL, alt VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL)');
        $this->addSql('INSERT INTO restaurant_image (id, restaurant_id, alt, updated_at) SELECT id, restaurant_id, alt, updated_at FROM __temp__restaurant_image');
        $this->addSql('DROP TABLE __temp__restaurant_image');
        $this->addSql('CREATE INDEX IDX_8F20B78EB1E7706E ON restaurant_image (restaurant_id)');
    }
}
